In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("heart.csv")

print("Ukuran dataset:", df.shape)
display(df.head())

Ukuran dataset: (269, 14)

,70,male,asymptomatic,130,322,0,ventricular_hypertrophy,109,no,2.4,flat,3,normal,Presence
0,67,female,non_anginal_pain,115,564,0,ventricular_hypertrophy,160,no,1.6,flat,0,reversable_defect,Absence
1,57,male,atypical_angina,124,261,0,normal,141,no,0.3,upsloping,0,reversable_defect,Presence
2,64,male,asymptomatic,128,263,0,normal,105,yes,0.2,flat,1,reversable_defect,Absence
3,74,female,atypical_angina,120,269,0,ventricular_hypertrophy,121,yes,0.2,upsloping,1,normal,Absence
4,65,male,asymptomatic,120,177,0,normal,140,no,0.4,upsloping,0,reversable_defect,Absence

In [ ]:
# Mengubah nama kolom menjadi lebih deskriptif

df = pd.read_csv("heart.csv", header=None)
df.columns = [
    "age",
    "sex",
    "cp",
    "trestbps",
    "chol",
    "fbs",
    "restecg",
    "thalach",
    "exang",
    "oldpeak",
    "slope",
    "ca",
    "thal",
    "Presence"
]

display(df.head())

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,Presence
0,70,male,asymptomatic,130,322,0,ventricular_hypertrophy,109,no,2.4,flat,3,normal,Presence
1,67,female,non_anginal_pain,115,564,0,ventricular_hypertrophy,160,no,1.6,flat,0,reversable_defect,Absence
2,57,male,atypical_angina,124,261,0,normal,141,no,0.3,upsloping,0,reversable_defect,Presence
3,64,male,asymptomatic,128,263,0,normal,105,yes,0.2,flat,1,reversable_defect,Absence
4,74,female,atypical_angina,120,269,0,ventricular_hypertrophy,121,yes,0.2,upsloping,1,normal,Absence

In [ ]:
# Menghitung jumlah data untuk setiap kelas

print(df["Presence"].value_counts())

Presence
Absence     150
Presence    120
Name: count, dtype: int64

In [4]:
# CEK TIPE DATA

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       270 non-null    int64
 1   sex       270 non-null    object
 2   cp        270 non-null    object
 3   trestbps  270 non-null    int64
 4   chol      270 non-null    int64
 5   fbs       270 non-null    int64
 6   restecg   270 non-null    object
 7   thalach   270 non-null    int64
 8   exang     270 non-null    object
 9   oldpeak   270 non-null    float64
 10  slope     270 non-null    object
 11  ca        270 non-null    int64
 12  thal      270 non-null    object
 13  Presence  270 non-null    object
dtypes: float64(1), int64(6), object(7)
memory usage: 29.7+ KB
None

In [5]:
# Check nilai unique pada setiap kolom fitur

for column in df.select_dtypes(include="object").columns:
    print(f"\n{column}:")
    print(df[column].unique())

sex:
['male' 'female']

cp:
['asymptomatic' 'non_anginal_pain' 'atypical_angina' 'typical_angina']

restecg:
['ventricular_hypertrophy' 'normal' 'wave_abnormality']

exang:
['no' 'yes']

slope:
['flat' 'upsloping' 'downsloping']

thal:
['normal' 'reversable_defect' 'fixed_defect']

Presence:
['Presence' 'Absence']

In [ ]:
# Konversi fitur kategorikal menjadi numerik

df["sex"] = df["sex"].map({
    "female": 0,
    "male": 1
})

df["cp"] = df["cp"].map({
    "asymptomatic": 0,
    "non_anginal_pain": 1,
    "atypical_angina": 2,
    "typical_angina": 3
})

df["restecg"] = df["restecg"].map({
    "normal": 0,
    "ventricular_hypertrophy": 1,
    "wave_abnormality": 2
})

df["exang"] = df["exang"].map({
    "no": 0,
    "yes": 1
})

df["slope"] = df["slope"].map({
    "upsloping": 0,
    "flat": 1,
    "downsloping": 2
})

df["thal"] = df["thal"].map({
    "normal": 0,
    "fixed_defect": 1,
    "reversable_defect": 2
})

df["Presence"] = df["Presence"].map({
    "Absence": 0,
    "Presence": 1
})

print(df.dtypes)

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
Presence      int64
dtype: object

In [8]:
# Cek hasil konversi
display(df.head())

print("\nTipe data:")
print(df.dtypes)

print("\nMissing value setelah konversi:")
print(df.isnull().sum())

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,Presence
0,70,1,0,130,322,0,1,109,0,2.4,1,3,0,1
1,67,0,1,115,564,0,1,160,0,1.6,1,0,2,0
2,57,1,2,124,261,0,0,141,0,0.3,0,0,2,1
3,64,1,0,128,263,0,0,105,1,0.2,1,1,2,0
4,74,0,2,120,269,0,1,121,1,0.2,0,1,0,0

Tipe data:
age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
Presence      int64
dtype: object

Missing value setelah konversi:
age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
Presence    0
dtype: int64

In [9]:
# Memisahkan fitur dan target

X = df.drop(columns=["Presence"])
y = df["Presence"]

print("X:")
display(X.head())

print("\ny:")
display(y.head())

X:

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,70,1,0,130,322,0,1,109,0,2.4,1,3,0
1,67,0,1,115,564,0,1,160,0,1.6,1,0,2
2,57,1,2,124,261,0,0,141,0,0.3,0,0,2
3,64,1,0,128,263,0,0,105,1,0.2,1,1,2
4,74,0,2,120,269,0,1,121,1,0.2,0,1,0

y:

0    1
1    0
2    1
3    0
4    0
Name: Presence, dtype: int64

In [10]:
# implementasi algoritma min-max

def min_max_normalization(data, new_min, new_max):
    minimum = data.min()
    maximum = data.max()

    return (data - minimum) * (new_max - new_min) / (maximum - minimum) + new_min

X_minmax = min_max_normalization(X, 0, 1)

print(X_minmax.head())

        age  sex        cp  trestbps      chol  fbs  restecg   thalach  exang  \
0  0.854167  1.0  0.000000  0.339623  0.447489  0.0      0.5  0.290076    0.0
1  0.791667  0.0  0.333333  0.198113  1.000000  0.0      0.5  0.679389    0.0
2  0.583333  1.0  0.666667  0.283019  0.308219  0.0      0.0  0.534351    0.0
3  0.729167  1.0  0.000000  0.320755  0.312785  0.0      0.0  0.259542    1.0
4  0.937500  0.0  0.666667  0.245283  0.326484  0.0      0.5  0.381679    1.0

    oldpeak  slope        ca  thal
0  0.387097    0.5  1.000000   0.0
1  0.258065    0.5  0.000000   1.0
2  0.048387    0.0  0.000000   1.0
3  0.032258    0.5  0.333333   1.0
4  0.032258    0.0  0.333333   0.0

In [11]:
# implementasi algoritma z-score

def z_score_normalization(data):
    mean = data.mean()
    std_dev = data.std()

    new_data = (data - mean) / std_dev
    return new_data

X_zscore = z_score_normalization(X)
print(X_zscore.head())

        age       sex        cp  trestbps      chol       fbs   restecg  \
0  1.708920  0.688222 -0.869313 -0.075270  1.399613 -0.416256  0.927586
1  1.379578 -1.447639  0.183219 -0.915060  6.081711 -0.416256  0.927586
2  0.281771  0.688222  1.235750 -0.411186  0.219415 -0.416256 -1.013874
3  1.050236  0.688222 -0.869313 -0.187242  0.258110 -0.416256 -1.013874
4  2.148043 -1.447639  1.235750 -0.635130  0.374195 -0.416256  0.927586

    thalach     exang   oldpeak     slope        ca      thal
0 -1.755947 -0.699923  1.178823  0.675165  2.468099 -0.857249
1  0.445582 -0.699923  0.480261  0.675165 -0.710216  1.227951
2 -0.374596 -0.699923 -0.654902 -0.952466 -0.710216  1.227951
3 -1.928616  1.423438 -0.742222  0.675165  0.349222  1.227951
4 -1.237940  1.423438 -0.742222 -0.952466  0.349222 -0.857249

In [12]:
# implementasi algoritma sigmoidal

def sigmoidal_normalization(data):

    x = (data - data.mean()) / data.std()
    new_data = (1 - np.exp(-x) / (1 + np.exp(-x)))

    return new_data

X_sigmoid = sigmoidal_normalization(X)
print(X_sigmoid.head())

        age       sex        cp  trestbps      chol       fbs   restecg  \
0  0.846696  0.665571  0.295397  0.481191  0.802123  0.397413  0.716585
1  0.798923  0.190365  0.545677  0.285966  0.997721  0.397413  0.716585
2  0.569980  0.665571  0.774823  0.398628  0.554635  0.397413  0.266222
3  0.740820  0.665571  0.295397  0.453326  0.564172  0.397413  0.266222
4  0.895486  0.190365  0.774823  0.346348  0.592472  0.397413  0.716585

    thalach     exang   oldpeak     slope        ca      thal
0  0.147299  0.331829  0.764736  0.662659  0.921875  0.297914
1  0.609588  0.331829  0.617810  0.662659  0.329551  0.773460
2  0.407431  0.331829  0.341886  0.278389  0.329551  0.773460
3  0.126904  0.805877  0.322518  0.662659  0.586429  0.773460
4  0.224795  0.805877  0.322518  0.278389  0.586429  0.297914

In [13]:
# Klasifikasi menggunakan k-NN (k = 1, k = 5, k = 9) dan decision tree (max_depth = 5)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

models = {
    "k-NN (k=1)": KNeighborsClassifier(n_neighbors=1),
    "k-NN (k=5)": KNeighborsClassifier(n_neighbors=5),
    "k-NN (k=9)": KNeighborsClassifier(n_neighbors=9),
    "Decision Tree (max_depth=5)": DecisionTreeClassifier(max_depth=5, random_state=42),
}

In [14]:
# Cross-validation menggunakan K-Fold (k = 4, k = 10) dan Leave-One-Out

from sklearn.model_selection import KFold, LeaveOneOut, cross_val_score

validations = {
    "4-Fold": KFold(n_splits=4, shuffle=True, random_state=42),
    "10-Fold": KFold(n_splits=10, shuffle=True, random_state=42),
    "Leave-One-Out": LeaveOneOut()
}

In [ ]:
results = []

normalizations = {
    "Min-Max": X_minmax,
    "Z-Score": X_zscore,
    "Sigmoidal": X_sigmoid
}

for norm_name, X_norm in normalizations.items():
    for model_name, model in models.items():
        for validation_name, validation in validations.items():
            scores = cross_val_score(
                model,
                X_norm,
                y,
                cv=validation,
                scoring="accuracy"
            )

            accuracy = scores.mean()
            error_ratio = 1 - accuracy
            results.append({
                "Normalisasi": norm_name,
                "Klasifikasi": model_name,
                "Validasi": validation_name,
                "Accuracy": accuracy,
                "Error Ratio": error_ratio
            })

results_df = pd.DataFrame(results)

print("Jumlah eksperimen:", len(results_df))
display(results_df)

Jumlah eksperimen: 36

,Normalisasi,Klasifikasi,Validasi,Accuracy,Error Ratio
0,Min-Max,k-NN (k=1),4-Fold,0.748025,0.251975
1,Min-Max,k-NN (k=1),10-Fold,0.766667,0.233333
2,Min-Max,k-NN (k=1),Leave-One-Out,0.755556,0.244444
3,Min-Max,k-NN (k=5),4-Fold,0.811073,0.188927
4,Min-Max,k-NN (k=5),10-Fold,0.800000,0.200000
5,Min-Max,k-NN (k=5),Leave-One-Out,0.803704,0.196296
6,Min-Max,k-NN (k=9),4-Fold,0.825889,0.174111
7,Min-Max,k-NN (k=9),10-Fold,0.833333,0.166667
8,Min-Max,k-NN (k=9),Leave-One-Out,0.837037,0.162963
9,Min-Max,Decision Tree (max_depth=5),4-Fold,0.773870,0.226130
10,Min-Max,Decision Tree (max_depth=5),10-Fold,0.781481,0.218519
11,Min-Max,Decision Tree (max_depth=5),Leave-One-Out,0.770370,0.229630
12,Z-Score,k-NN (k=1),4-Fold,0.796093,0.203907
13,Z-Score,k-NN (k=1),10-Fold,0.770370,0.229630
14,Z-Score,k-NN (k=1),Leave-One-Out,0.759259,0.240741
15,Z-Score,k-NN (k=5),4-Fold,0.837138,0.162862
16,Z-Score,k-NN (k=5),10-Fold,0.818519,0.181481
17,Z-Score,k-NN (k=5),Leave-One-Out,0.825926,0.174074
18,Z-Score,k-NN (k=9),4-Fold,0.837083,0.162917
19,Z-Score,k-NN (k=9),10-Fold,0.837037,0.162963
20,Z-Score,k-NN (k=9),Leave-One-Out,0.822222,0.177778
21,Z-Score,Decision Tree (max_depth=5),4-Fold,0.773870,0.226130
22,Z-Score,Decision Tree (max_depth=5),10-Fold,0.781481,0.218519
23,Z-Score,Decision Tree (max_depth=5),Leave-One-Out,0.770370,0.229630
24,Sigmoidal,k-NN (k=1),4-Fold,0.803665,0.196335
25,Sigmoidal,k-NN (k=1),10-Fold,0.777778,0.222222
26,Sigmoidal,k-NN (k=1),Leave-One-Out,0.766667,0.233333
27,Sigmoidal,k-NN (k=5),4-Fold,0.829565,0.170435
28,Sigmoidal,k-NN (k=5),10-Fold,0.825926,0.174074
29,Sigmoidal,k-NN (k=5),Leave-One-Out,0.818519,0.181481
30,Sigmoidal,k-NN (k=9),4-Fold,0.829675,0.170325
31,Sigmoidal,k-NN (k=9),10-Fold,0.822222,0.177778
32,Sigmoidal,k-NN (k=9),Leave-One-Out,0.822222,0.177778
33,Sigmoidal,Decision Tree (max_depth=5),4-Fold,0.773924,0.226076
34,Sigmoidal,Decision Tree (max_depth=5),10-Fold,0.781481,0.218519
35,Sigmoidal,Decision Tree (max_depth=5),Leave-One-Out,0.770370,0.229630

In [16]:
results_df["Accuracy (%)"] = results_df["Accuracy"] * 100
results_df["Error Ratio (%)"] = results_df["Error Ratio"] * 100

hasil = results_df[
    [
        "Normalisasi",
        "Klasifikasi",
        "Validasi",
        "Accuracy (%)",
        "Error Ratio (%)"
    ]
]

display(hasil)

,Normalisasi,Klasifikasi,Validasi,Accuracy (%),Error Ratio (%)
0,Min-Max,k-NN (k=1),4-Fold,74.802458,25.197542
1,Min-Max,k-NN (k=1),10-Fold,76.666667,23.333333
2,Min-Max,k-NN (k=1),Leave-One-Out,75.555556,24.444444
3,Min-Max,k-NN (k=5),4-Fold,81.107331,18.892669
4,Min-Max,k-NN (k=5),10-Fold,80.000000,20.000000
5,Min-Max,k-NN (k=5),Leave-One-Out,80.370370,19.629630
6,Min-Max,k-NN (k=9),4-Fold,82.588894,17.411106
7,Min-Max,k-NN (k=9),10-Fold,83.333333,16.666667
8,Min-Max,k-NN (k=9),Leave-One-Out,83.703704,16.296296
9,Min-Max,Decision Tree (max_depth=5),4-Fold,77.386962,22.613038
10,Min-Max,Decision Tree (max_depth=5),10-Fold,78.148148,21.851852
11,Min-Max,Decision Tree (max_depth=5),Leave-One-Out,77.037037,22.962963
12,Z-Score,k-NN (k=1),4-Fold,79.609306,20.390694
13,Z-Score,k-NN (k=1),10-Fold,77.037037,22.962963
14,Z-Score,k-NN (k=1),Leave-One-Out,75.925926,24.074074
15,Z-Score,k-NN (k=5),4-Fold,83.713784,16.286216
16,Z-Score,k-NN (k=5),10-Fold,81.851852,18.148148
17,Z-Score,k-NN (k=5),Leave-One-Out,82.592593,17.407407
18,Z-Score,k-NN (k=9),4-Fold,83.708297,16.291703
19,Z-Score,k-NN (k=9),10-Fold,83.703704,16.296296
20,Z-Score,k-NN (k=9),Leave-One-Out,82.222222,17.777778
21,Z-Score,Decision Tree (max_depth=5),4-Fold,77.386962,22.613038
22,Z-Score,Decision Tree (max_depth=5),10-Fold,78.148148,21.851852
23,Z-Score,Decision Tree (max_depth=5),Leave-One-Out,77.037037,22.962963
24,Sigmoidal,k-NN (k=1),4-Fold,80.366550,19.633450
25,Sigmoidal,k-NN (k=1),10-Fold,77.777778,22.222222
26,Sigmoidal,k-NN (k=1),Leave-One-Out,76.666667,23.333333
27,Sigmoidal,k-NN (k=5),4-Fold,82.956541,17.043459
28,Sigmoidal,k-NN (k=5),10-Fold,82.592593,17.407407
29,Sigmoidal,k-NN (k=5),Leave-One-Out,81.851852,18.148148
30,Sigmoidal,k-NN (k=9),4-Fold,82.967515,17.032485
31,Sigmoidal,k-NN (k=9),10-Fold,82.222222,17.777778
32,Sigmoidal,k-NN (k=9),Leave-One-Out,82.222222,17.777778
33,Sigmoidal,Decision Tree (max_depth=5),4-Fold,77.392450,22.607550
34,Sigmoidal,Decision Tree (max_depth=5),10-Fold,78.148148,21.851852
35,Sigmoidal,Decision Tree (max_depth=5),Leave-One-Out,77.037037,22.962963

In [17]:
hasil_terbaik = hasil.sort_values(
    by="Error Ratio (%)"
).reset_index(drop=True)

display(hasil_terbaik)

,Normalisasi,Klasifikasi,Validasi,Accuracy (%),Error Ratio (%)
0,Z-Score,k-NN (k=5),4-Fold,83.713784,16.286216
1,Z-Score,k-NN (k=9),4-Fold,83.708297,16.291703
2,Z-Score,k-NN (k=9),10-Fold,83.703704,16.296296
3,Min-Max,k-NN (k=9),Leave-One-Out,83.703704,16.296296
4,Min-Max,k-NN (k=9),10-Fold,83.333333,16.666667
5,Sigmoidal,k-NN (k=9),4-Fold,82.967515,17.032485
6,Sigmoidal,k-NN (k=5),4-Fold,82.956541,17.043459
7,Z-Score,k-NN (k=5),Leave-One-Out,82.592593,17.407407
8,Sigmoidal,k-NN (k=5),10-Fold,82.592593,17.407407
9,Min-Max,k-NN (k=9),4-Fold,82.588894,17.411106
10,Sigmoidal,k-NN (k=9),10-Fold,82.222222,17.777778
11,Z-Score,k-NN (k=9),Leave-One-Out,82.222222,17.777778
12,Sigmoidal,k-NN (k=9),Leave-One-Out,82.222222,17.777778
13,Z-Score,k-NN (k=5),10-Fold,81.851852,18.148148
14,Sigmoidal,k-NN (k=5),Leave-One-Out,81.851852,18.148148
15,Min-Max,k-NN (k=5),4-Fold,81.107331,18.892669
16,Min-Max,k-NN (k=5),Leave-One-Out,80.370370,19.629630
17,Sigmoidal,k-NN (k=1),4-Fold,80.366550,19.633450
18,Min-Max,k-NN (k=5),10-Fold,80.000000,20.000000
19,Z-Score,k-NN (k=1),4-Fold,79.609306,20.390694
20,Min-Max,Decision Tree (max_depth=5),10-Fold,78.148148,21.851852
21,Z-Score,Decision Tree (max_depth=5),10-Fold,78.148148,21.851852
22,Sigmoidal,Decision Tree (max_depth=5),10-Fold,78.148148,21.851852
23,Sigmoidal,k-NN (k=1),10-Fold,77.777778,22.222222
24,Sigmoidal,Decision Tree (max_depth=5),4-Fold,77.392450,22.607550
25,Min-Max,Decision Tree (max_depth=5),4-Fold,77.386962,22.613038
26,Z-Score,Decision Tree (max_depth=5),4-Fold,77.386962,22.613038
27,Min-Max,Decision Tree (max_depth=5),Leave-One-Out,77.037037,22.962963
28,Sigmoidal,Decision Tree (max_depth=5),Leave-One-Out,77.037037,22.962963
29,Z-Score,k-NN (k=1),10-Fold,77.037037,22.962963
30,Z-Score,Decision Tree (max_depth=5),Leave-One-Out,77.037037,22.962963
31,Min-Max,k-NN (k=1),10-Fold,76.666667,23.333333
32,Sigmoidal,k-NN (k=1),Leave-One-Out,76.666667,23.333333
33,Z-Score,k-NN (k=1),Leave-One-Out,75.925926,24.074074
34,Min-Max,k-NN (k=1),Leave-One-Out,75.555556,24.444444
35,Min-Max,k-NN (k=1),4-Fold,74.802458,25.197542